server:
  port: 443
  ssl:
    key-store: classpath:myWeb.jks
    key-store-password: xtv0yEB9
    key-store-type: JKS
    key-alias: alias

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    root: warn
    com.xw: info
  file: log/blog-pro.log

mybatis:
  type-aliases-package: com.xw.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true







